framework:
    translator: ~

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                success_handler: login_success_handler
                csrf_token_generator: security.csrf.token_manager
                default_target_path: fos_user_profile_show
                always_use_default_target_path: false
            
            logout:
                path:       fos_user_security_logout
                target:     /login
            anonymous:    true
            
            remember_me:
                secret:        %secret%
                lifetime:      604800
                path:          /
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }