<?php

namespace Sfb\SiteBundle\Repository;

/**
 * GenreProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
