<?php

namespace Sfb\SiteBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function search($page,$title)
	{
		$query = $this 	->createQueryBuilder('p')
						->where('p.title LIKE :title')
						->setParameter('title','%'.$title.'%')
						->orderBy('p.id','ASC')
						->getQuery();
		$query  ->setFirstResult(($page-1) * 5)
                ->setMaxResults(5);
        return new Paginator($query);
	}
}
